# app/config/routing.yml
home:
  pattern: /
  defaults: { _controller: AppBundle:Home:index }
  options:
    expose: true

categories:
  pattern: /categories
  defaults: { _controller: AppBundle:Default:index }
  options:
    expose: true

category.show:
  pattern: /blog/{page}
  defaults: { _controller: AppBundle:Default:blog, page: 1 }
  options:
    expose: true